=== Artalz/VezbaIspit/magacin.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns="http://www.w3schools.com" elementFormDefault="qualified" targetNamespace="http://www.w3schools.com" xmlns:xs="http://www.w3.org/2001/XMLSchema">

<xs:element name="Magacin">
    <xs:complexType>
        <xs:sequence minOccurs="1" maxOccurs="unbounded">
            <xs:element ref="Artikal" />
        </xs:sequence>
    </xs:complexType>
</xs:element>
<xs:element name="Artikal">
    <xs:complexType>
        <xs:sequence>
            <xs:element ref="Naziv" />
            <xs:element ref="DatumIzrade" />
            <xs:element ref="Cena" />
            <xs:element ref="Kompanija" />
            <xs:element minOccurs="1" maxOccurs="unbounded" ref="Email" />
        </xs:sequence>
    </xs:complexType>
</xs:element>
<xs:element name="Naziv">
    <xs:complexType>
        <xs:sequence>
            <xs:restriction base="xs:string">
                <xs:minLength value="3" />
                <xs:maxLength value="30" />
                <xs:attribute name="sifra" use="required" />
            </xs:restriction>
        </xs:sequence>
    </xs:complexType>
</xs:element>
<xs:element name="DatumIzrade">
    <xs:complexType>
        <xs:sequence>
            <xs:element ref="Dan" />
            <xs:element ref="Mesec" />
            <xs:element ref="Godina" />
        </xs:sequence>
    </xs:complexType>
</xs:element>
<xs:element name="Dan">
    <xs:simpleType>
        <xs:restriction base="xs:string">
            <xs:pattern value="[1-9]|[1-2][0-9]|3[0-1]" />
        </xs:restriction>
    </xs:simpleType>
</xs:element>
<xs:element name="Mesec">
    <xs:simpleType>
        <xs:restriction base="xs:string">
            <xs:pattern value="[1-9]|1[0-2]" />
        </xs:restriction>
    </xs:simpleType>
</xs:element>
<xs:element name="Godina" type="xs:string" />
<xs:element name="Cena">
    <xs:complexType>
        <xs:simpleContent>
            <xs:extension base="nonNegativeInteger">
                <xs:attribute default="din" name="tip">
                    <xs:simpleType>
                        <xs:restriction base="xs:NMTOKEN">
                            <xs:enumeration value="din" />
                            <xs:enumeration value="eur" />
                        </xs:restriction>
                    </xs:simpleType>
                </xs:attribute>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>
</xs:element>

<xs:simpleType name="nonNegativeInteger">
    <xs:restriction base="xs:integer">
        <xs:minInclusive value="0" />
    </xs:restriction>
</xs:simpleType>

<xs:element name="Kompanija">
    <xs:complexType>
        <xs:sequence>
            <xs:element ref="ImeKompanije" />
            <xs:element ref="Adresa" />
        </xs:sequence>
    </xs:complexType>
</xs:element>
<xs:element name="ImeKompanije" type="xs:string" />
<xs:element minOccurs="1" maxOccurs="unbounded" name="Adresa"/>

<xs:element name="Email">
    <xs:complexType>
        <xs:simpleContent>
            <xs:extension base="emailRestrikcija">
                <xs:attribute name="tip" use="required">
                    <xs:simpleType>
                        </xs:restriction base="xs:NMTOKEN">
                            <xs:enumeration value="privatni"/>
                            <xs:enumeration value="sluzbeni"/>
                        </xs:restriction>
                    </xs:simpleType>    
                </xs:attribute>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>
</xs:element>

<xs:simpleType name="emailRestrikcija">
    <xs:restriction base="xs:string">
        <xs:pattern value="\c{5,20}[A-Z]{1}[0-9]{1}@\c{4,8}.com" />
    </xs:restriction>
</xs:simpleType>

=== Artalz/VezbaIspit/magacin.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Magacin System "magacin.dtd">
<Magacin xmlns="http://www.w3schools.com"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="http://www.w3schools.com magacin.xsd">
<Artikal>
    <Naziv sifra="1">Jogurt</Naziv>
    <DatumIzrade>
        <Dan>3</Dan>
        <Mesec>7</Mesec>
        <Godina>2010</Godina>
    </DatumIzrade>
    <Cena tip="din">120</Cena>
    <Kompanija>
        <ImeKompanije>Imlek</ImeKompanije>
        <Adresa>Beograd</Adresa>
    </Kompanija>
    <Email tip="sluzbeni">email@mail.com</Email>
    <Email tip="privatni">emailp@mail.com</Email>
</Artikal>
